FROM golang:1.15.2-alpine3.12

RUN apk add git

RUN mkdir -p /go/src/stock-portfolio-web

WORKDIR /go/src/stock-portfolio-web

COPY . /go/src/stock-portfolio-web

COPY . /usr/local/go/src/stock-portfolio-web

RUN go get ./...

RUN go install stock-portfolio-web

CMD ["/go/bin/stock-portfolio-web"]

EXPOSE 8080
