version: '3.8'
services:
  app:
    container_name: web_api
    hostname: web_api
    restart: on-failure:3
    build:
      context: .
      dockerfile: DockerFile
    ports:
    - "8080:8080"
    links:
      - "db:database"
      
  db:
    container_name: web_db
    hostname: web_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
    - "3306:3306"
