version: '3.8'
services:
  db:
    container_name: web_db
    hostname: web_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
    - "3306:3306"
    volumes:
    - ../db_setup.sql:/docker-entrypoint-initdb.d/setup.sql
    
  app:
    container_name: web_api
    hostname: web_api
    restart: on-failure:3
    build:
      context: .
      dockerfile: DockerFile
    ports:
    - "8080:8080"
    links:
      - "db:database"
